In [ ]:
import os
import torch

from utils.tensor_dump import load_tensors



In [ ]:
torch.set_printoptions(profile='full')
def compare_tensors(path: str, position_id: int, tag: str):
  file_list = os.listdir(path)

  def filter_func(fname: str, device: str) -> bool:
    elem = fname.split("_")
    return elem[0] == device and elem[2] == str(position_id) and elem[3] == tag

  for cuda_file in file_list:
    if filter_func(cuda_file, "cuda"):
      for cpu_file in file_list:
        if filter_func(cpu_file, "cpu"):
          print("compare: {} and {}".format(cuda_file, cpu_file))
          cpu_tensor = torch.load(os.path.join(path, cpu_file))[0]
          cuda_tensor = torch.load(os.path.join(path, cuda_file))[0]
          print(cpu_tensor.size())
          print(cuda_tensor.size())
          # print(cpu_tensor)
          # print(cuda_tensor)
          print(cpu_tensor[:,0])
          print(cuda_tensor[:,0])
          max_diff = (cpu_tensor - cuda_tensor).abs().max() 
          print("max_diff: {}".format(max_diff))
          print("-----------------------------")
          assert torch.allclose(cuda_tensor, cpu_tensor)

compare_tensors("/root/vllm/tensors/", 0, "final")

In [41]:
cpu_tensor = torch.load("/root/vllm/benchmarks/cpu")
cuda_tensor = torch.load("/root/vllm/benchmarks/cuda").cpu()
max_diff = (cpu_tensor - cuda_tensor).abs().max() 
print("max_diff: {}".format(max_diff))
print(cpu_tensor[0,0:20])
print(cuda_tensor[0,0:20])


max_diff: 8.821487426757812e-06
tensor([3.3582e-11, 3.4702e-12, 6.9577e-01, 2.0882e-09, 3.3022e-09, 2.1645e-10,
        1.8608e-09, 1.3997e-10, 3.0255e-10, 3.2734e-10, 6.3559e-11, 1.7852e-10,
        1.9816e-06, 1.1011e-01, 4.6696e-09, 1.4018e-10, 3.3603e-11, 1.0441e-09,
        6.3565e-11, 2.2148e-10])
tensor([3.3582e-11, 3.4701e-12, 6.9576e-01, 2.0882e-09, 3.3022e-09, 2.1645e-10,
        1.8608e-09, 1.3997e-10, 3.0255e-10, 3.2733e-10, 6.3559e-11, 1.7852e-10,
        1.9815e-06, 1.1011e-01, 4.6696e-09, 1.4018e-10, 3.3604e-11, 1.0441e-09,
        6.3565e-11, 2.2148e-10])


CPU
hidden: tensor([[-0.3567, -2.8620,  3.0712,  ..., -2.4590, -1.7950,  0.0178]])
logits: tensor([[-1.0825, -3.3523, 22.6718,  ..., -0.7116, -1.3651,  3.8542]])
probs: tensor([[3.3582e-11, 3.4702e-12, 6.9577e-01,  ..., 4.8661e-11, 2.5315e-11,
         4.6785e-09]])
logprobs: tensor([[-24.1170, -26.3868,  -0.3627,  ..., -23.7461, -24.3996, -19.1803]])
next: tensor([2])

hidden: tensor([[-0.3567, -2.8620,  3.0712,  ..., -2.4590, -1.7950,  0.0178]],
       device='cuda:0')
logits: tensor([[-1.0825, -3.3523, 22.6718,  ..., -0.7116, -1.3651,  3.8542]],
       device='cuda:0')
probs: tensor([[3.3582e-11, 3.4701e-12, 6.9576e-01,  ..., 4.8661e-11, 2.5315e-11,
         4.6785e-09]], device='cuda:0')
logprobs: tensor([[-24.1170, -26.3868,  -0.3627,  ..., -23.7461, -24.3996, -19.1803]],
       device='cuda:0')
next: tensor([13], device='cuda:0')

In [ ]:
tensor([    1,   306,  1996,   596, 18872,   304, 10683,  1749,  2669,  1813,
         1048,  5798,  4080,  2866,  1461, 29879,  7927,  7598,   297,  1771,
          275, 29890,  1662,   363,   278, 21411,   310,   263,  3271, 20348,
          297,  1771,   275, 29890,  1662, 29892,  8314, 29889,   306,   674,
         2367,   366,  2999,  2472,   393,   366,   505,   304,  2050,  1316,
          408,   278,  8118,   515,   278,  2246, 24034,  6515,  7395, 29892,
          322,  3646, 29361, 29889,  1938,   366,  2274, 29973,     0,     0,
            0,     0], device='cuda:0')
tensor([13,  0,  0,  0,  0,  0,  0,  0], device='cuda:0')
tensor([13,  0,  0,  0,  0,  0,  0,  0], device='cuda:0')
tensor([12148,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')
tensor([3867,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([592,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([411,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([278,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([337,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([17625,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')
tensor([1426,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([363,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([278,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([5798,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([4080,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([2866,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([1461,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([29879,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')
tensor([7927,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([7598,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([297,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([1771,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([275,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([29890,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')
tensor([1662,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([2669,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([1813,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([29892,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')
tensor([12515,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')
tensor([297,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([3458,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([278,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([21411,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')
tensor([310,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([263,   0,   0,   0,   0,   0,   0,   0], device='cuda:0')
tensor([3271,    0,    0,    0,    0,    0,    0,    0], device='cuda:0')
tensor([20348,     0,     0,     0,     0,     0,     0,     0],
       device='cuda:0')